# DOWNLOADING NECESSARY LIBRARIES

In [1]:
pip install numpy

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: numpy in c:\users\lab4-studentpc11\appdata\local\packages\pythonsoftwarefoundation.python.3.13_qbz5n2kfra8p0\localcache\local-packages\python313\site-packages (2.2.2)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 24.3.1 -> 25.0
[notice] To update, run: C:\Users\LAB4-StudentPC11\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip

In [2]:
pip install pandas

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: pandas in c:\users\lab4-studentpc11\appdata\local\packages\pythonsoftwarefoundation.python.3.13_qbz5n2kfra8p0\localcache\local-packages\python313\site-packages (2.2.3)
Requirement already satisfied: numpy>=1.26.0 in c:\users\lab4-studentpc11\appdata\local\packages\pythonsoftwarefoundation.python.3.13_qbz5n2kfra8p0\localcache\local-packages\python313\site-packages (from pandas) (2.2.2)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\lab4-studentpc11\appdata\local\packages\pythonsoftwarefoundation.python.3.13_qbz5n2kfra8p0\localcache\local-packages\python313\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\lab4-studentpc11\appdata\local\packages\pythonsoftwarefoundation.python.3.13_qbz5n2kfra8p0\localcache\local-packages\python313\site-packages (from pandas) (2024.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\lab4-studentpc11\appdata\local\packages\pythonsoftwarefoundation.python.3.13_qbz5n2kfra8p0\localcache\local-packages\python313\site-packages (from pandas) (2025.1)
Requirement already satisfied: six>=1.5 in c:\users\lab4-studentpc11\appdata\local\packages\pythonsoftwarefoundation.python.3.13_qbz5n2kfra8p0\localcache\local-packages\python313\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 24.3.1 -> 25.0
[notice] To update, run: C:\Users\LAB4-StudentPC11\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip

In [3]:
pip install matplotlib

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: matplotlib in c:\users\lab4-studentpc11\appdata\local\packages\pythonsoftwarefoundation.python.3.13_qbz5n2kfra8p0\localcache\local-packages\python313\site-packages (3.10.0)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\lab4-studentpc11\appdata\local\packages\pythonsoftwarefoundation.python.3.13_qbz5n2kfra8p0\localcache\local-packages\python313\site-packages (from matplotlib) (1.3.1)
Requirement already satisfied: cycler>=0.10 in c:\users\lab4-studentpc11\appdata\local\packages\pythonsoftwarefoundation.python.3.13_qbz5n2kfra8p0\localcache\local-packages\python313\site-packages (from matplotlib) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\lab4-studentpc11\appdata\local\packages\pythonsoftwarefoundation.python.3.13_qbz5n2kfra8p0\localcache\local-packages\python313\site-packages (from matplotlib) (4.55.4)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\users\lab4-studentpc11\appdata\local\packages\pythonsoftwarefoundation.python.3.13_qbz5n2kfra8p0\localcache\local-packages\python313\site-packages (from matplotlib) (1.4.8)
Requirement already satisfied: numpy>=1.23 in c:\users\lab4-studentpc11\appdata\local\packages\pythonsoftwarefoundation.python.3.13_qbz5n2kfra8p0\localcache\local-packages\python313\site-packages (from matplotlib) (2.2.2)
Requirement already satisfied: packaging>=20.0 in c:\users\lab4-studentpc11\appdata\local\packages\pythonsoftwarefoundation.python.3.13_qbz5n2kfra8p0\localcache\local-packages\python313\site-packages (from matplotlib) (24.2)
Requirement already satisfied: pillow>=8 in c:\users\lab4-studentpc11\appdata\local\packages\pythonsoftwarefoundation.python.3.13_qbz5n2kfra8p0\localcache\local-packages\python313\site-packages (from matplotlib) (11.1.0)
Requirement already satisfied: pyparsing>=2.3.1 in c:\users\lab4-studentpc11\appdata\local\packages\pythonsoftwarefoundation.python.3.13_qbz5n2kfra8p0\localcache\local-packages\python313\site-packages (from matplotlib) (3.2.1)
Requirement already satisfied: python-dateutil>=2.7 in c:\users\lab4-studentpc11\appdata\local\packages\pythonsoftwarefoundation.python.3.13_qbz5n2kfra8p0\localcache\local-packages\python313\site-packages (from matplotlib) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in c:\users\lab4-studentpc11\appdata\local\packages\pythonsoftwarefoundation.python.3.13_qbz5n2kfra8p0\localcache\local-packages\python313\site-packages (from python-dateutil>=2.7->matplotlib) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 24.3.1 -> 25.0
[notice] To update, run: C:\Users\LAB4-StudentPC11\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip

In [4]:
pip install seaborn

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: seaborn in c:\users\lab4-studentpc11\appdata\local\packages\pythonsoftwarefoundation.python.3.13_qbz5n2kfra8p0\localcache\local-packages\python313\site-packages (0.13.2)
Requirement already satisfied: numpy!=1.24.0,>=1.20 in c:\users\lab4-studentpc11\appdata\local\packages\pythonsoftwarefoundation.python.3.13_qbz5n2kfra8p0\localcache\local-packages\python313\site-packages (from seaborn) (2.2.2)
Requirement already satisfied: pandas>=1.2 in c:\users\lab4-studentpc11\appdata\local\packages\pythonsoftwarefoundation.python.3.13_qbz5n2kfra8p0\localcache\local-packages\python313\site-packages (from seaborn) (2.2.3)
Requirement already satisfied: matplotlib!=3.6.1,>=3.4 in c:\users\lab4-studentpc11\appdata\local\packages\pythonsoftwarefoundation.python.3.13_qbz5n2kfra8p0\localcache\local-packages\python313\site-packages (from seaborn) (3.10.0)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\lab4-studentpc11\appdata\local\packages\pythonsoftwarefoundation.python.3.13_qbz5n2kfra8p0\localcache\local-packages\python313\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (1.3.1)
Requirement already satisfied: cycler>=0.10 in c:\users\lab4-studentpc11\appdata\local\packages\pythonsoftwarefoundation.python.3.13_qbz5n2kfra8p0\localcache\local-packages\python313\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\lab4-studentpc11\appdata\local\packages\pythonsoftwarefoundation.python.3.13_qbz5n2kfra8p0\localcache\local-packages\python313\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (4.55.4)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\users\lab4-studentpc11\appdata\local\packages\pythonsoftwarefoundation.python.3.13_qbz5n2kfra8p0\localcache\local-packages\python313\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (1.4.8)
Requirement already satisfied: packaging>=20.0 in c:\users\lab4-studentpc11\appdata\local\packages\pythonsoftwarefoundation.python.3.13_qbz5n2kfra8p0\localcache\local-packages\python313\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (24.2)
Requirement already satisfied: pillow>=8 in c:\users\lab4-studentpc11\appdata\local\packages\pythonsoftwarefoundation.python.3.13_qbz5n2kfra8p0\localcache\local-packages\python313\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (11.1.0)
Requirement already satisfied: pyparsing>=2.3.1 in c:\users\lab4-studentpc11\appdata\local\packages\pythonsoftwarefoundation.python.3.13_qbz5n2kfra8p0\localcache\local-packages\python313\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (3.2.1)
Requirement already satisfied: python-dateutil>=2.7 in c:\users\lab4-studentpc11\appdata\local\packages\pythonsoftwarefoundation.python.3.13_qbz5n2kfra8p0\localcache\local-packages\python313\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\lab4-studentpc11\appdata\local\packages\pythonsoftwarefoundation.python.3.13_qbz5n2kfra8p0\localcache\local-packages\python313\site-packages (from pandas>=1.2->seaborn) (2024.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\lab4-studentpc11\appdata\local\packages\pythonsoftwarefoundation.python.3.13_qbz5n2kfra8p0\localcache\local-packages\python313\site-packages (from pandas>=1.2->seaborn) (2025.1)
Requirement already satisfied: six>=1.5 in c:\users\lab4-studentpc11\appdata\local\packages\pythonsoftwarefoundation.python.3.13_qbz5n2kfra8p0\localcache\local-packages\python313\site-packages (from python-dateutil>=2.7->matplotlib!=3.6.1,>=3.4->seaborn) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 24.3.1 -> 25.0
[notice] To update, run: C:\Users\LAB4-StudentPC11\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip

# IMPORTING LIBRARIES

In [5]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# IMPORTING DATASETS TO DATA FRAME

In [6]:
#variable_name / name

In [7]:
birds = pd.read_csv('datasets\\penguins.csv')

In [8]:
birds

,rowid,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex,year
0,1,Adelie,Torgersen,39.1,18.7,181.0,3750.0,male,2007
1,2,Adelie,Torgersen,39.5,17.4,186.0,3800.0,female,2007
2,3,Adelie,Torgersen,40.3,18.0,195.0,3250.0,female,2007
3,4,Adelie,Torgersen,NaN,NaN,NaN,NaN,NaN,2007
4,5,Adelie,Torgersen,36.7,19.3,193.0,3450.0,female,2007
...,...,...,...,...,...,...,...,...,...
339,340,Chinstrap,Dream,55.8,19.8,207.0,4000.0,male,2009
340,341,Chinstrap,Dream,43.5,18.1,202.0,3400.0,female,2009
341,342,Chinstrap,Dream,49.6,18.2,193.0,3775.0,male,2009
342,343,Chinstrap,Dream,50.8,19.0,210.0,4100.0,male,2009
343,344,Chinstrap,Dream,50.2,18.7,198.0,3775.0,female,2009

In [9]:
birds.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 344 entries, 0 to 343
Data columns (total 9 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   rowid              344 non-null    int64
 1   species            344 non-null    object
 2   island             344 non-null    object
 3   bill_length_mm     342 non-null    float64
 4   bill_depth_mm      342 non-null    float64
 5   flipper_length_mm  342 non-null    float64
 6   body_mass_g        342 non-null    float64
 7   sex                333 non-null    object
 8   year               344 non-null    int64
dtypes: float64(4), int64(2), object(3)
memory usage: 24.3+ KB

In [10]:
birds.isnull().sum()

rowid                 0
species               0
island                0
bill_length_mm        2
bill_depth_mm         2
flipper_length_mm     2
body_mass_g           2
sex                  11
year                  0
dtype: int64

# DESCRIPTIVE ANALYTICS

In [11]:
birds.describe()

,rowid,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,year
count,344.000000,342.000000,342.000000,342.000000,342.000000,344.000000
mean,172.500000,43.921930,17.151170,200.915205,4201.754386,2008.029070
std,99.448479,5.459584,1.974793,14.061714,801.954536,0.818356
min,1.000000,32.100000,13.100000,172.000000,2700.000000,2007.000000
25%,86.750000,39.225000,15.600000,190.000000,3550.000000,2007.000000
50%,172.500000,44.450000,17.300000,197.000000,4050.000000,2008.000000
75%,258.250000,48.500000,18.700000,213.000000,4750.000000,2009.000000
max,344.000000,59.600000,21.500000,231.000000,6300.000000,2009.000000

# to flip the describe table t - transpose

In [12]:
birds.describe().T

,count,mean,std,min,25%,50%,75%,max
rowid,344.0,172.500000,99.448479,1.0,86.750,172.50,258.25,344.0
bill_length_mm,342.0,43.921930,5.459584,32.1,39.225,44.45,48.50,59.6
bill_depth_mm,342.0,17.151170,1.974793,13.1,15.600,17.30,18.70,21.5
flipper_length_mm,342.0,200.915205,14.061714,172.0,190.000,197.00,213.00,231.0
body_mass_g,342.0,4201.754386,801.954536,2700.0,3550.000,4050.00,4750.00,6300.0
year,344.0,2008.029070,0.818356,2007.0,2007.000,2008.00,2009.00,2009.0

In [13]:
birds['body_mass_g']

0      3750.0
1      3800.0
2      3250.0
3         NaN
4      3450.0
        ...
339    4000.0
340    3400.0
341    3775.0
342    4100.0
343    3775.0
Name: body_mass_g, Length: 344, dtype: float64

# HOW TO DEFINE YOUR OWN COLUMN

In [14]:
birds['weight'] = np.round(birds['body_mass_g'] / 1000 ,1)
birds

,rowid,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex,year,weight
0,1,Adelie,Torgersen,39.1,18.7,181.0,3750.0,male,2007,3.8
1,2,Adelie,Torgersen,39.5,17.4,186.0,3800.0,female,2007,3.8
2,3,Adelie,Torgersen,40.3,18.0,195.0,3250.0,female,2007,3.2
3,4,Adelie,Torgersen,NaN,NaN,NaN,NaN,NaN,2007,NaN
4,5,Adelie,Torgersen,36.7,19.3,193.0,3450.0,female,2007,3.4
...,...,...,...,...,...,...,...,...,...,...
339,340,Chinstrap,Dream,55.8,19.8,207.0,4000.0,male,2009,4.0
340,341,Chinstrap,Dream,43.5,18.1,202.0,3400.0,female,2009,3.4
341,342,Chinstrap,Dream,49.6,18.2,193.0,3775.0,male,2009,3.8
342,343,Chinstrap,Dream,50.8,19.0,210.0,4100.0,male,2009,4.1
343,344,Chinstrap,Dream,50.2,18.7,198.0,3775.0,female,2009,3.8

# WHAT TO DO WITH NULL VALUES ?

In [15]:
birds['body_mass_g'].mean()

np.float64(4201.754385964912)

In [16]:
birds['sex'].mode()

0    male
Name: sex, dtype: object

In [17]:
birds['bill_length_mm'] = birds['bill_length_mm'].fillna(birds['bill_length_mm'].mean())

In [18]:
birds['body_mass_g'] = birds['body_mass_g'].fillna(birds['body_mass_g'].mean())

In [19]:
birds['bill_depth_mm'] = birds['bill_depth_mm'].fillna(birds['bill_depth_mm'].mean())

In [20]:
birds['flipper_length_mm'] = birds['flipper_length_mm'].fillna(birds['flipper_length_mm'].mean())

In [21]:
birds.isnull().sum()

rowid                 0
species               0
island                0
bill_length_mm        0
bill_depth_mm         0
flipper_length_mm     0
body_mass_g           0
sex                  11
year                  0
weight                2
dtype: int64

In [22]:
birds['sex'] = birds['sex'].fillna(birds['sex'].mode()[0])

In [23]:
birds.isnull().sum()

rowid                0
species              0
island               0
bill_length_mm       0
bill_depth_mm        0
flipper_length_mm    0
body_mass_g          0
sex                  0
year                 0
weight               2
dtype: int64

In [24]:
birds.isnull().sum()

rowid                0
species              0
island               0
bill_length_mm       0
bill_depth_mm        0
flipper_length_mm    0
body_mass_g          0
sex                  0
year                 0
weight               2
dtype: int64

In [25]:
birds['weight'] = birds['weight'].fillna(birds['weight'].mode()[0])

In [26]:
birds.isnull().sum()

rowid                0
species              0
island               0
bill_length_mm       0
bill_depth_mm        0
flipper_length_mm    0
body_mass_g          0
sex                  0
year                 0
weight               0
dtype: int64

In [27]:
birds

,rowid,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex,year,weight
0,1,Adelie,Torgersen,39.10000,18.70000,181.000000,3750.000000,male,2007,3.8
1,2,Adelie,Torgersen,39.50000,17.40000,186.000000,3800.000000,female,2007,3.8
2,3,Adelie,Torgersen,40.30000,18.00000,195.000000,3250.000000,female,2007,3.2
3,4,Adelie,Torgersen,43.92193,17.15117,200.915205,4201.754386,male,2007,3.6
4,5,Adelie,Torgersen,36.70000,19.30000,193.000000,3450.000000,female,2007,3.4
...,...,...,...,...,...,...,...,...,...,...
339,340,Chinstrap,Dream,55.80000,19.80000,207.000000,4000.000000,male,2009,4.0
340,341,Chinstrap,Dream,43.50000,18.10000,202.000000,3400.000000,female,2009,3.4
341,342,Chinstrap,Dream,49.60000,18.20000,193.000000,3775.000000,male,2009,3.8
342,343,Chinstrap,Dream,50.80000,19.00000,210.000000,4100.000000,male,2009,4.1
343,344,Chinstrap,Dream,50.20000,18.70000,198.000000,3775.000000,female,2009,3.8

In [28]:
birds['weight'] = np.round(birds['body_mass_g'] / 1000 ,2)
birds

,rowid,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex,year,weight
0,1,Adelie,Torgersen,39.10000,18.70000,181.000000,3750.000000,male,2007,3.75
1,2,Adelie,Torgersen,39.50000,17.40000,186.000000,3800.000000,female,2007,3.80
2,3,Adelie,Torgersen,40.30000,18.00000,195.000000,3250.000000,female,2007,3.25
3,4,Adelie,Torgersen,43.92193,17.15117,200.915205,4201.754386,male,2007,4.20
4,5,Adelie,Torgersen,36.70000,19.30000,193.000000,3450.000000,female,2007,3.45
...,...,...,...,...,...,...,...,...,...,...
339,340,Chinstrap,Dream,55.80000,19.80000,207.000000,4000.000000,male,2009,4.00
340,341,Chinstrap,Dream,43.50000,18.10000,202.000000,3400.000000,female,2009,3.40
341,342,Chinstrap,Dream,49.60000,18.20000,193.000000,3775.000000,male,2009,3.78
342,343,Chinstrap,Dream,50.80000,19.00000,210.000000,4100.000000,male,2009,4.10
343,344,Chinstrap,Dream,50.20000,18.70000,198.000000,3775.000000,female,2009,3.78

In [29]:
birds.isnull().sum()

rowid                0
species              0
island               0
bill_length_mm       0
bill_depth_mm        0
flipper_length_mm    0
body_mass_g          0
sex                  0
year                 0
weight               0
dtype: int64

# COLUM DATA TYPES

In [30]:
birds['year'] = birds['year'].astype('category')

In [31]:
birds.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 344 entries, 0 to 343
Data columns (total 10 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   rowid              344 non-null    int64
 1   species            344 non-null    object
 2   island             344 non-null    object
 3   bill_length_mm     344 non-null    float64
 4   bill_depth_mm      344 non-null    float64
 5   flipper_length_mm  344 non-null    float64
 6   body_mass_g        344 non-null    float64
 7   sex                344 non-null    object
 8   year               344 non-null    category
 9   weight             344 non-null    float64
dtypes: category(1), float64(5), int64(1), object(3)
memory usage: 24.8+ KB

In [32]:
birds['species'] = birds['species'].astype('category')

In [33]:
birds['island'] = birds['island'].astype('category')

In [34]:
birds['sex'] = birds['sex'].astype('category')

In [35]:
birds['rowid'] = birds['rowid'].astype('category')

In [36]:
birds.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 344 entries, 0 to 343
Data columns (total 10 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   rowid              344 non-null    category
 1   species            344 non-null    category
 2   island             344 non-null    category
 3   bill_length_mm     344 non-null    float64
 4   bill_depth_mm      344 non-null    float64
 5   flipper_length_mm  344 non-null    float64
 6   body_mass_g        344 non-null    float64
 7   sex                344 non-null    category
 8   year               344 non-null    category
 9   weight             344 non-null    float64
dtypes: category(5), float64(5)
memory usage: 26.9 KB

In [37]:
birds['species'] == "Chinstrap"

0      False
1      False
2      False
3      False
4      False
       ...
339     True
340     True
341     True
342     True
343     True
Name: species, Length: 344, dtype: bool

In [38]:
birds[birds['species'] == "Chinstrap"].count()

rowid                68
species              68
island               68
bill_length_mm       68
bill_depth_mm        68
flipper_length_mm    68
body_mass_g          68
sex                  68
year                 68
weight               68
dtype: int64

In [39]:
birds[birds['species'] == "Gentoo"].count()

rowid                124
species              124
island               124
bill_length_mm       124
bill_depth_mm        124
flipper_length_mm    124
body_mass_g          124
sex                  124
year                 124
weight               124
dtype: int64

In [40]:
birds[birds['species'] == "Adelie"].count()

rowid                152
species              152
island               152
bill_length_mm       152
bill_depth_mm        152
flipper_length_mm    152
body_mass_g          152
sex                  152
year                 152
weight               152
dtype: int64

#  1 HOW MANY GENTOO SPECIES HAVE WEIGHT MORE THAN 3KG??

In [41]:
birds['species'] == "Gentoo"

0      False
1      False
2      False
3      False
4      False
       ...
339    False
340    False
341    False
342    False
343    False
Name: species, Length: 344, dtype: bool

In [42]:
birds['body_mass_g'] > 3000

0      True
1      True
2      True
3      True
4      True
       ...
339    True
340    True
341    True
342    True
343    True
Name: body_mass_g, Length: 344, dtype: bool

In [43]:
g = birds[
    birds['species'] == "Gentoo"]
g[g['weight'] > 5].count()

rowid                61
species              61
island               61
bill_length_mm       61
bill_depth_mm        61
flipper_length_mm    61
body_mass_g          61
sex                  61
year                 61
weight               61
dtype: int64

# 2 HOW MANY GENTOO SPECIES HAVE WEIGHT LESS THAN 3kg??

In [50]:
g = birds[
    birds['species'] == "Gentoo"]
g[g['weight'] < 5].count()

rowid                57
species              57
island               57
bill_length_mm       57
bill_depth_mm        57
flipper_length_mm    57
body_mass_g          57
sex                  57
year                 57
weight               57
dtype: int64

In [47]:
birds['species'] == 'Gentoo'

0      False
1      False
2      False
3      False
4      False
       ...
339    False
340    False
341    False
342    False
343    False
Name: species, Length: 344, dtype: bool

In [48]:
birds['island'] == 'Gentoo'

0      False
1      False
2      False
3      False
4      False
       ...
339    False
340    False
341    False
342    False
343    False
Name: island, Length: 344, dtype: bool

In [49]:
birds[birds['island'] == 'Gentoo']

Empty DataFrame
Columns: [rowid, species, island, bill_length_mm, bill_depth_mm, flipper_length_mm, body_mass_g, sex, year, weight]
Index: []