# DOWNLOADING NECESSARY LIBRARIES

In [1]:
pip install numpy

Defaulting to user installation because normal site-packages is not writeableNote: you may need to restart the kernel to use updated packages.

Requirement already satisfied: numpy in c:\users\lab4-studentpc11\appdata\local\packages\pythonsoftwarefoundation.python.3.13_qbz5n2kfra8p0\localcache\local-packages\python313\site-packages (2.2.2)

[notice] A new release of pip is available: 24.3.1 -> 25.0.1
[notice] To update, run: C:\Users\LAB4-StudentPC11\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip

In [2]:
pip install pandas

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: pandas in c:\users\lab4-studentpc11\appdata\local\packages\pythonsoftwarefoundation.python.3.13_qbz5n2kfra8p0\localcache\local-packages\python313\site-packages (2.2.3)
Requirement already satisfied: numpy>=1.26.0 in c:\users\lab4-studentpc11\appdata\local\packages\pythonsoftwarefoundation.python.3.13_qbz5n2kfra8p0\localcache\local-packages\python313\site-packages (from pandas) (2.2.2)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\lab4-studentpc11\appdata\local\packages\pythonsoftwarefoundation.python.3.13_qbz5n2kfra8p0\localcache\local-packages\python313\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\lab4-studentpc11\appdata\local\packages\pythonsoftwarefoundation.python.3.13_qbz5n2kfra8p0\localcache\local-packages\python313\site-packages (from pandas) (2024.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\lab4-studentpc11\appdata\local\packages\pythonsoftwarefoundation.python.3.13_qbz5n2kfra8p0\localcache\local-packages\python313\site-packages (from pandas) (2025.1)
Requirement already satisfied: six>=1.5 in c:\users\lab4-studentpc11\appdata\local\packages\pythonsoftwarefoundation.python.3.13_qbz5n2kfra8p0\localcache\local-packages\python313\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 24.3.1 -> 25.0.1
[notice] To update, run: C:\Users\LAB4-StudentPC11\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip

In [3]:
pip install matplotlib

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: matplotlib in c:\users\lab4-studentpc11\appdata\local\packages\pythonsoftwarefoundation.python.3.13_qbz5n2kfra8p0\localcache\local-packages\python313\site-packages (3.10.0)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\lab4-studentpc11\appdata\local\packages\pythonsoftwarefoundation.python.3.13_qbz5n2kfra8p0\localcache\local-packages\python313\site-packages (from matplotlib) (1.3.1)
Requirement already satisfied: cycler>=0.10 in c:\users\lab4-studentpc11\appdata\local\packages\pythonsoftwarefoundation.python.3.13_qbz5n2kfra8p0\localcache\local-packages\python313\site-packages (from matplotlib) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\lab4-studentpc11\appdata\local\packages\pythonsoftwarefoundation.python.3.13_qbz5n2kfra8p0\localcache\local-packages\python313\site-packages (from matplotlib) (4.55.4)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\users\lab4-studentpc11\appdata\local\packages\pythonsoftwarefoundation.python.3.13_qbz5n2kfra8p0\localcache\local-packages\python313\site-packages (from matplotlib) (1.4.8)
Requirement already satisfied: numpy>=1.23 in c:\users\lab4-studentpc11\appdata\local\packages\pythonsoftwarefoundation.python.3.13_qbz5n2kfra8p0\localcache\local-packages\python313\site-packages (from matplotlib) (2.2.2)
Requirement already satisfied: packaging>=20.0 in c:\users\lab4-studentpc11\appdata\local\packages\pythonsoftwarefoundation.python.3.13_qbz5n2kfra8p0\localcache\local-packages\python313\site-packages (from matplotlib) (24.2)
Requirement already satisfied: pillow>=8 in c:\users\lab4-studentpc11\appdata\local\packages\pythonsoftwarefoundation.python.3.13_qbz5n2kfra8p0\localcache\local-packages\python313\site-packages (from matplotlib) (11.1.0)
Requirement already satisfied: pyparsing>=2.3.1 in c:\users\lab4-studentpc11\appdata\local\packages\pythonsoftwarefoundation.python.3.13_qbz5n2kfra8p0\localcache\local-packages\python313\site-packages (from matplotlib) (3.2.1)
Requirement already satisfied: python-dateutil>=2.7 in c:\users\lab4-studentpc11\appdata\local\packages\pythonsoftwarefoundation.python.3.13_qbz5n2kfra8p0\localcache\local-packages\python313\site-packages (from matplotlib) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in c:\users\lab4-studentpc11\appdata\local\packages\pythonsoftwarefoundation.python.3.13_qbz5n2kfra8p0\localcache\local-packages\python313\site-packages (from python-dateutil>=2.7->matplotlib) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 24.3.1 -> 25.0.1
[notice] To update, run: C:\Users\LAB4-StudentPC11\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip

In [4]:
pip install seaborn

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: seaborn in c:\users\lab4-studentpc11\appdata\local\packages\pythonsoftwarefoundation.python.3.13_qbz5n2kfra8p0\localcache\local-packages\python313\site-packages (0.13.2)
Requirement already satisfied: numpy!=1.24.0,>=1.20 in c:\users\lab4-studentpc11\appdata\local\packages\pythonsoftwarefoundation.python.3.13_qbz5n2kfra8p0\localcache\local-packages\python313\site-packages (from seaborn) (2.2.2)
Requirement already satisfied: pandas>=1.2 in c:\users\lab4-studentpc11\appdata\local\packages\pythonsoftwarefoundation.python.3.13_qbz5n2kfra8p0\localcache\local-packages\python313\site-packages (from seaborn) (2.2.3)
Requirement already satisfied: matplotlib!=3.6.1,>=3.4 in c:\users\lab4-studentpc11\appdata\local\packages\pythonsoftwarefoundation.python.3.13_qbz5n2kfra8p0\localcache\local-packages\python313\site-packages (from seaborn) (3.10.0)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\lab4-studentpc11\appdata\local\packages\pythonsoftwarefoundation.python.3.13_qbz5n2kfra8p0\localcache\local-packages\python313\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (1.3.1)
Requirement already satisfied: cycler>=0.10 in c:\users\lab4-studentpc11\appdata\local\packages\pythonsoftwarefoundation.python.3.13_qbz5n2kfra8p0\localcache\local-packages\python313\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\lab4-studentpc11\appdata\local\packages\pythonsoftwarefoundation.python.3.13_qbz5n2kfra8p0\localcache\local-packages\python313\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (4.55.4)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\users\lab4-studentpc11\appdata\local\packages\pythonsoftwarefoundation.python.3.13_qbz5n2kfra8p0\localcache\local-packages\python313\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (1.4.8)
Requirement already satisfied: packaging>=20.0 in c:\users\lab4-studentpc11\appdata\local\packages\pythonsoftwarefoundation.python.3.13_qbz5n2kfra8p0\localcache\local-packages\python313\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (24.2)
Requirement already satisfied: pillow>=8 in c:\users\lab4-studentpc11\appdata\local\packages\pythonsoftwarefoundation.python.3.13_qbz5n2kfra8p0\localcache\local-packages\python313\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (11.1.0)
Requirement already satisfied: pyparsing>=2.3.1 in c:\users\lab4-studentpc11\appdata\local\packages\pythonsoftwarefoundation.python.3.13_qbz5n2kfra8p0\localcache\local-packages\python313\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (3.2.1)
Requirement already satisfied: python-dateutil>=2.7 in c:\users\lab4-studentpc11\appdata\local\packages\pythonsoftwarefoundation.python.3.13_qbz5n2kfra8p0\localcache\local-packages\python313\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\lab4-studentpc11\appdata\local\packages\pythonsoftwarefoundation.python.3.13_qbz5n2kfra8p0\localcache\local-packages\python313\site-packages (from pandas>=1.2->seaborn) (2024.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\lab4-studentpc11\appdata\local\packages\pythonsoftwarefoundation.python.3.13_qbz5n2kfra8p0\localcache\local-packages\python313\site-packages (from pandas>=1.2->seaborn) (2025.1)
Requirement already satisfied: six>=1.5 in c:\users\lab4-studentpc11\appdata\local\packages\pythonsoftwarefoundation.python.3.13_qbz5n2kfra8p0\localcache\local-packages\python313\site-packages (from python-dateutil>=2.7->matplotlib!=3.6.1,>=3.4->seaborn) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 24.3.1 -> 25.0.1
[notice] To update, run: C:\Users\LAB4-StudentPC11\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip

# IMPORTING LIBRARIES

In [5]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import scipy as sp

# IMPORTING DATASETS TO DATA FRAME

In [6]:
#variable_name / name

In [7]:
birds = pd.read_csv('datasets\\penguins.csv')

In [8]:
birds

,rowid,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex,year
0,1,Adelie,Torgersen,39.1,18.7,181.0,3750.0,male,2007
1,2,Adelie,Torgersen,39.5,17.4,186.0,3800.0,female,2007
2,3,Adelie,Torgersen,40.3,18.0,195.0,3250.0,female,2007
3,4,Adelie,Torgersen,NaN,NaN,NaN,NaN,NaN,2007
4,5,Adelie,Torgersen,36.7,19.3,193.0,3450.0,female,2007
...,...,...,...,...,...,...,...,...,...
339,340,Chinstrap,Dream,55.8,19.8,207.0,4000.0,male,2009
340,341,Chinstrap,Dream,43.5,18.1,202.0,3400.0,female,2009
341,342,Chinstrap,Dream,49.6,18.2,193.0,3775.0,male,2009
342,343,Chinstrap,Dream,50.8,19.0,210.0,4100.0,male,2009
343,344,Chinstrap,Dream,50.2,18.7,198.0,3775.0,female,2009

In [9]:
birds.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 344 entries, 0 to 343
Data columns (total 9 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   rowid              344 non-null    int64
 1   species            344 non-null    object
 2   island             344 non-null    object
 3   bill_length_mm     342 non-null    float64
 4   bill_depth_mm      342 non-null    float64
 5   flipper_length_mm  342 non-null    float64
 6   body_mass_g        342 non-null    float64
 7   sex                333 non-null    object
 8   year               344 non-null    int64
dtypes: float64(4), int64(2), object(3)
memory usage: 24.3+ KB

In [10]:
birds.isnull().sum()

rowid                 0
species               0
island                0
bill_length_mm        2
bill_depth_mm         2
flipper_length_mm     2
body_mass_g           2
sex                  11
year                  0
dtype: int64

# DESCRIPTIVE ANALYTICS

In [11]:
birds.describe()

,rowid,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,year
count,344.000000,342.000000,342.000000,342.000000,342.000000,344.000000
mean,172.500000,43.921930,17.151170,200.915205,4201.754386,2008.029070
std,99.448479,5.459584,1.974793,14.061714,801.954536,0.818356
min,1.000000,32.100000,13.100000,172.000000,2700.000000,2007.000000
25%,86.750000,39.225000,15.600000,190.000000,3550.000000,2007.000000
50%,172.500000,44.450000,17.300000,197.000000,4050.000000,2008.000000
75%,258.250000,48.500000,18.700000,213.000000,4750.000000,2009.000000
max,344.000000,59.600000,21.500000,231.000000,6300.000000,2009.000000

# to flip the describe table t - transpose

In [12]:
birds.describe().T

,count,mean,std,min,25%,50%,75%,max
rowid,344.0,172.500000,99.448479,1.0,86.750,172.50,258.25,344.0
bill_length_mm,342.0,43.921930,5.459584,32.1,39.225,44.45,48.50,59.6
bill_depth_mm,342.0,17.151170,1.974793,13.1,15.600,17.30,18.70,21.5
flipper_length_mm,342.0,200.915205,14.061714,172.0,190.000,197.00,213.00,231.0
body_mass_g,342.0,4201.754386,801.954536,2700.0,3550.000,4050.00,4750.00,6300.0
year,344.0,2008.029070,0.818356,2007.0,2007.000,2008.00,2009.00,2009.0

In [13]:
birds['body_mass_g']

0      3750.0
1      3800.0
2      3250.0
3         NaN
4      3450.0
        ...
339    4000.0
340    3400.0
341    3775.0
342    4100.0
343    3775.0
Name: body_mass_g, Length: 344, dtype: float64

# HOW TO DEFINE YOUR OWN COLUMN

In [14]:
birds['weight'] = np.round(birds['body_mass_g'] / 1000 ,1)
birds

,rowid,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex,year,weight
0,1,Adelie,Torgersen,39.1,18.7,181.0,3750.0,male,2007,3.8
1,2,Adelie,Torgersen,39.5,17.4,186.0,3800.0,female,2007,3.8
2,3,Adelie,Torgersen,40.3,18.0,195.0,3250.0,female,2007,3.2
3,4,Adelie,Torgersen,NaN,NaN,NaN,NaN,NaN,2007,NaN
4,5,Adelie,Torgersen,36.7,19.3,193.0,3450.0,female,2007,3.4
...,...,...,...,...,...,...,...,...,...,...
339,340,Chinstrap,Dream,55.8,19.8,207.0,4000.0,male,2009,4.0
340,341,Chinstrap,Dream,43.5,18.1,202.0,3400.0,female,2009,3.4
341,342,Chinstrap,Dream,49.6,18.2,193.0,3775.0,male,2009,3.8
342,343,Chinstrap,Dream,50.8,19.0,210.0,4100.0,male,2009,4.1
343,344,Chinstrap,Dream,50.2,18.7,198.0,3775.0,female,2009,3.8

# WHAT TO DO WITH NULL VALUES ?

In [15]:
birds['body_mass_g'].mean()

np.float64(4201.754385964912)

In [16]:
birds['sex'].mode()

0    male
Name: sex, dtype: object

In [17]:
birds['bill_length_mm'] = birds['bill_length_mm'].fillna(birds['bill_length_mm'].mean())

In [18]:
birds['body_mass_g'] = birds['body_mass_g'].fillna(birds['body_mass_g'].mean())

In [19]:
birds['bill_depth_mm'] = birds['bill_depth_mm'].fillna(birds['bill_depth_mm'].mean())

In [20]:
birds['flipper_length_mm'] = birds['flipper_length_mm'].fillna(birds['flipper_length_mm'].mean())

In [21]:
birds.isnull().sum()

rowid                 0
species               0
island                0
bill_length_mm        0
bill_depth_mm         0
flipper_length_mm     0
body_mass_g           0
sex                  11
year                  0
weight                2
dtype: int64

In [22]:
birds['sex'] = birds['sex'].fillna(birds['sex'].mode()[0])

In [23]:
birds.isnull().sum()

rowid                0
species              0
island               0
bill_length_mm       0
bill_depth_mm        0
flipper_length_mm    0
body_mass_g          0
sex                  0
year                 0
weight               2
dtype: int64

In [24]:
birds.isnull().sum()

rowid                0
species              0
island               0
bill_length_mm       0
bill_depth_mm        0
flipper_length_mm    0
body_mass_g          0
sex                  0
year                 0
weight               2
dtype: int64

In [25]:
birds['weight'] = birds['weight'].fillna(birds['weight'].mode()[0])

In [26]:
birds.isnull().sum()

rowid                0
species              0
island               0
bill_length_mm       0
bill_depth_mm        0
flipper_length_mm    0
body_mass_g          0
sex                  0
year                 0
weight               0
dtype: int64

In [27]:
birds

,rowid,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex,year,weight
0,1,Adelie,Torgersen,39.10000,18.70000,181.000000,3750.000000,male,2007,3.8
1,2,Adelie,Torgersen,39.50000,17.40000,186.000000,3800.000000,female,2007,3.8
2,3,Adelie,Torgersen,40.30000,18.00000,195.000000,3250.000000,female,2007,3.2
3,4,Adelie,Torgersen,43.92193,17.15117,200.915205,4201.754386,male,2007,3.6
4,5,Adelie,Torgersen,36.70000,19.30000,193.000000,3450.000000,female,2007,3.4
...,...,...,...,...,...,...,...,...,...,...
339,340,Chinstrap,Dream,55.80000,19.80000,207.000000,4000.000000,male,2009,4.0
340,341,Chinstrap,Dream,43.50000,18.10000,202.000000,3400.000000,female,2009,3.4
341,342,Chinstrap,Dream,49.60000,18.20000,193.000000,3775.000000,male,2009,3.8
342,343,Chinstrap,Dream,50.80000,19.00000,210.000000,4100.000000,male,2009,4.1
343,344,Chinstrap,Dream,50.20000,18.70000,198.000000,3775.000000,female,2009,3.8

In [28]:
birds['weight'] = np.round(birds['body_mass_g'] / 1000 ,2)
birds

,rowid,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex,year,weight
0,1,Adelie,Torgersen,39.10000,18.70000,181.000000,3750.000000,male,2007,3.75
1,2,Adelie,Torgersen,39.50000,17.40000,186.000000,3800.000000,female,2007,3.80
2,3,Adelie,Torgersen,40.30000,18.00000,195.000000,3250.000000,female,2007,3.25
3,4,Adelie,Torgersen,43.92193,17.15117,200.915205,4201.754386,male,2007,4.20
4,5,Adelie,Torgersen,36.70000,19.30000,193.000000,3450.000000,female,2007,3.45
...,...,...,...,...,...,...,...,...,...,...
339,340,Chinstrap,Dream,55.80000,19.80000,207.000000,4000.000000,male,2009,4.00
340,341,Chinstrap,Dream,43.50000,18.10000,202.000000,3400.000000,female,2009,3.40
341,342,Chinstrap,Dream,49.60000,18.20000,193.000000,3775.000000,male,2009,3.78
342,343,Chinstrap,Dream,50.80000,19.00000,210.000000,4100.000000,male,2009,4.10
343,344,Chinstrap,Dream,50.20000,18.70000,198.000000,3775.000000,female,2009,3.78

In [29]:
birds.isnull().sum()

rowid                0
species              0
island               0
bill_length_mm       0
bill_depth_mm        0
flipper_length_mm    0
body_mass_g          0
sex                  0
year                 0
weight               0
dtype: int64

# COLUM DATA TYPES

In [30]:
birds['year'] = birds['year'].astype('category')

In [31]:
birds.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 344 entries, 0 to 343
Data columns (total 10 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   rowid              344 non-null    int64
 1   species            344 non-null    object
 2   island             344 non-null    object
 3   bill_length_mm     344 non-null    float64
 4   bill_depth_mm      344 non-null    float64
 5   flipper_length_mm  344 non-null    float64
 6   body_mass_g        344 non-null    float64
 7   sex                344 non-null    object
 8   year               344 non-null    category
 9   weight             344 non-null    float64
dtypes: category(1), float64(5), int64(1), object(3)
memory usage: 24.8+ KB

In [32]:
birds['species'] = birds['species'].astype('category')

In [33]:
birds['island'] = birds['island'].astype('category')

In [34]:
birds['sex'] = birds['sex'].astype('category')

In [35]:
birds['rowid'] = birds['rowid'].astype('category')

In [36]:
birds.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 344 entries, 0 to 343
Data columns (total 10 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   rowid              344 non-null    category
 1   species            344 non-null    category
 2   island             344 non-null    category
 3   bill_length_mm     344 non-null    float64
 4   bill_depth_mm      344 non-null    float64
 5   flipper_length_mm  344 non-null    float64
 6   body_mass_g        344 non-null    float64
 7   sex                344 non-null    category
 8   year               344 non-null    category
 9   weight             344 non-null    float64
dtypes: category(5), float64(5)
memory usage: 26.9 KB

In [37]:
birds['species'] == "Chinstrap"

0      False
1      False
2      False
3      False
4      False
       ...
339     True
340     True
341     True
342     True
343     True
Name: species, Length: 344, dtype: bool

In [38]:
birds[birds['species'] == "Chinstrap"].count()

rowid                68
species              68
island               68
bill_length_mm       68
bill_depth_mm        68
flipper_length_mm    68
body_mass_g          68
sex                  68
year                 68
weight               68
dtype: int64

In [39]:
birds[birds['species'] == "Gentoo"].count()

rowid                124
species              124
island               124
bill_length_mm       124
bill_depth_mm        124
flipper_length_mm    124
body_mass_g          124
sex                  124
year                 124
weight               124
dtype: int64

In [40]:
birds[birds['species'] == "Adelie"].count()

rowid                152
species              152
island               152
bill_length_mm       152
bill_depth_mm        152
flipper_length_mm    152
body_mass_g          152
sex                  152
year                 152
weight               152
dtype: int64

#  1 HOW MANY GENTOO SPECIES HAVE WEIGHT MORE THAN 3KG??

In [41]:
birds['species'] == "Gentoo"

0      False
1      False
2      False
3      False
4      False
       ...
339    False
340    False
341    False
342    False
343    False
Name: species, Length: 344, dtype: bool

In [42]:
birds['body_mass_g'] > 3000

0      True
1      True
2      True
3      True
4      True
       ...
339    True
340    True
341    True
342    True
343    True
Name: body_mass_g, Length: 344, dtype: bool

In [43]:
g = birds[
    birds['species'] == "Gentoo"]
g[g['weight'] > 5].count()

rowid                61
species              61
island               61
bill_length_mm       61
bill_depth_mm        61
flipper_length_mm    61
body_mass_g          61
sex                  61
year                 61
weight               61
dtype: int64

# 2 HOW MANY GENTOO SPECIES HAVE WEIGHT LESS THAN 3kg??

In [44]:
g = birds[
    birds['species'] == "Gentoo"]
g[g['weight'] < 5].count()

rowid                57
species              57
island               57
bill_length_mm       57
bill_depth_mm        57
flipper_length_mm    57
body_mass_g          57
sex                  57
year                 57
weight               57
dtype: int64

In [45]:
birds['species'] == 'Gentoo'

0      False
1      False
2      False
3      False
4      False
       ...
339    False
340    False
341    False
342    False
343    False
Name: species, Length: 344, dtype: bool

In [46]:
birds['island'] == 'Gentoo'

0      False
1      False
2      False
3      False
4      False
       ...
339    False
340    False
341    False
342    False
343    False
Name: island, Length: 344, dtype: bool

In [47]:
birds[birds['island'] == 'Gentoo']

Empty DataFrame
Columns: [rowid, species, island, bill_length_mm, bill_depth_mm, flipper_length_mm, body_mass_g, sex, year, weight]
Index: []

In [48]:
def getPenguin(penguin_name, island):
    return birds[(birds['species'] == penguin_name) &(birds['island'] == island)]

In [49]:
gentoo_dream = getPenguin("Gentoo", "Dream")
gentoo_dream.info()

<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 10 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   rowid              0 non-null      category
 1   species            0 non-null      category
 2   island             0 non-null      category
 3   bill_length_mm     0 non-null      float64
 4   bill_depth_mm      0 non-null      float64
 5   flipper_length_mm  0 non-null      float64
 6   body_mass_g        0 non-null      float64
 7   sex                0 non-null      category
 8   year               0 non-null      category
 9   weight             0 non-null      float64
dtypes: category(5), float64(5)
memory usage: 11.3 KB

In [50]:
gentoo_torg = getPenguin("Gentoo", "Torgersen")
gentoo_torg.info()

<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 10 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   rowid              0 non-null      category
 1   species            0 non-null      category
 2   island             0 non-null      category
 3   bill_length_mm     0 non-null      float64
 4   bill_depth_mm      0 non-null      float64
 5   flipper_length_mm  0 non-null      float64
 6   body_mass_g        0 non-null      float64
 7   sex                0 non-null      category
 8   year               0 non-null      category
 9   weight             0 non-null      float64
dtypes: category(5), float64(5)
memory usage: 11.3 KB

In [51]:
gentoo_Ade = getPenguin("Gentoo", "Adelie")
gentoo_Ade.info()

<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 10 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   rowid              0 non-null      category
 1   species            0 non-null      category
 2   island             0 non-null      category
 3   bill_length_mm     0 non-null      float64
 4   bill_depth_mm      0 non-null      float64
 5   flipper_length_mm  0 non-null      float64
 6   body_mass_g        0 non-null      float64
 7   sex                0 non-null      category
 8   year               0 non-null      category
 9   weight             0 non-null      float64
dtypes: category(5), float64(5)
memory usage: 11.3 KB

In [52]:
birds['island']

0      Torgersen
1      Torgersen
2      Torgersen
3      Torgersen
4      Torgersen
         ...
339        Dream
340        Dream
341        Dream
342        Dream
343        Dream
Name: island, Length: 344, dtype: category
Categories (3, object): ['Biscoe', 'Dream', 'Torgersen']

In [53]:
birds['weight'] = np.round(birds['body_mass_g'] / 1000, 1)
birds

,rowid,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex,year,weight
0,1,Adelie,Torgersen,39.10000,18.70000,181.000000,3750.000000,male,2007,3.8
1,2,Adelie,Torgersen,39.50000,17.40000,186.000000,3800.000000,female,2007,3.8
2,3,Adelie,Torgersen,40.30000,18.00000,195.000000,3250.000000,female,2007,3.2
3,4,Adelie,Torgersen,43.92193,17.15117,200.915205,4201.754386,male,2007,4.2
4,5,Adelie,Torgersen,36.70000,19.30000,193.000000,3450.000000,female,2007,3.4
...,...,...,...,...,...,...,...,...,...,...
339,340,Chinstrap,Dream,55.80000,19.80000,207.000000,4000.000000,male,2009,4.0
340,341,Chinstrap,Dream,43.50000,18.10000,202.000000,3400.000000,female,2009,3.4
341,342,Chinstrap,Dream,49.60000,18.20000,193.000000,3775.000000,male,2009,3.8
342,343,Chinstrap,Dream,50.80000,19.00000,210.000000,4100.000000,male,2009,4.1
343,344,Chinstrap,Dream,50.20000,18.70000,198.000000,3775.000000,female,2009,3.8

In [54]:
birds['bill_length_mm'] = birds['bill_length_mm'].fillna(birds['bill_length_mm'].mean())

In [55]:
birds['bill_depth_mm'] = birds['bill_depth_mm'].fillna(birds['bill_depth_mm'].mean())

In [56]:
birds['flipper_length_mm'] = birds['flipper_length_mm'].fillna(birds['flipper_length_mm'].mean())

In [57]:
birds['body_mass_g'] = birds['body_mass_g'].fillna(birds['body_mass_g'].mean())

In [58]:
birds['sex'] = birds['sex'].fillna(birds['sex'].mode()[0])

In [59]:
birds['weight'] = np.round(birds['body_mass_g'] / 1000, 2)
birds

,rowid,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex,year,weight
0,1,Adelie,Torgersen,39.10000,18.70000,181.000000,3750.000000,male,2007,3.75
1,2,Adelie,Torgersen,39.50000,17.40000,186.000000,3800.000000,female,2007,3.80
2,3,Adelie,Torgersen,40.30000,18.00000,195.000000,3250.000000,female,2007,3.25
3,4,Adelie,Torgersen,43.92193,17.15117,200.915205,4201.754386,male,2007,4.20
4,5,Adelie,Torgersen,36.70000,19.30000,193.000000,3450.000000,female,2007,3.45
...,...,...,...,...,...,...,...,...,...,...
339,340,Chinstrap,Dream,55.80000,19.80000,207.000000,4000.000000,male,2009,4.00
340,341,Chinstrap,Dream,43.50000,18.10000,202.000000,3400.000000,female,2009,3.40
341,342,Chinstrap,Dream,49.60000,18.20000,193.000000,3775.000000,male,2009,3.78
342,343,Chinstrap,Dream,50.80000,19.00000,210.000000,4100.000000,male,2009,4.10
343,344,Chinstrap,Dream,50.20000,18.70000,198.000000,3775.000000,female,2009,3.78

In [60]:
birds.isnull().sum()

rowid                0
species              0
island               0
bill_length_mm       0
bill_depth_mm        0
flipper_length_mm    0
body_mass_g          0
sex                  0
year                 0
weight               0
dtype: int64

In [61]:
birds['rowid'] = birds['rowid'].astype('category')
birds['year'] = birds['year'].astype('category')
birds['species'] = birds['species'].astype('category')
birds['island'] = birds['island'].astype('category')
birds['sex'] = birds['sex'].astype('category')

# filtering data based from columns

In [62]:
birds['body_mass_g']

0      3750.000000
1      3800.000000
2      3250.000000
3      4201.754386
4      3450.000000
          ...
339    4000.000000
340    3400.000000
341    3775.000000
342    4100.000000
343    3775.000000
Name: body_mass_g, Length: 344, dtype: float64

In [63]:
birds['sex']

0        male
1      female
2      female
3        male
4      female
        ...
339      male
340    female
341      male
342      male
343    female
Name: sex, Length: 344, dtype: category
Categories (2, object): ['female', 'male']

# How to create your own column

In [64]:
birds['weight'] = np.round(birds['body_mass_g'] / 1000,1)

In [65]:
birds

,rowid,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex,year,weight
0,1,Adelie,Torgersen,39.10000,18.70000,181.000000,3750.000000,male,2007,3.8
1,2,Adelie,Torgersen,39.50000,17.40000,186.000000,3800.000000,female,2007,3.8
2,3,Adelie,Torgersen,40.30000,18.00000,195.000000,3250.000000,female,2007,3.2
3,4,Adelie,Torgersen,43.92193,17.15117,200.915205,4201.754386,male,2007,4.2
4,5,Adelie,Torgersen,36.70000,19.30000,193.000000,3450.000000,female,2007,3.4
...,...,...,...,...,...,...,...,...,...,...
339,340,Chinstrap,Dream,55.80000,19.80000,207.000000,4000.000000,male,2009,4.0
340,341,Chinstrap,Dream,43.50000,18.10000,202.000000,3400.000000,female,2009,3.4
341,342,Chinstrap,Dream,49.60000,18.20000,193.000000,3775.000000,male,2009,3.8
342,343,Chinstrap,Dream,50.80000,19.00000,210.000000,4100.000000,male,2009,4.1
343,344,Chinstrap,Dream,50.20000,18.70000,198.000000,3775.000000,female,2009,3.8

# Does any of the birds species live exclusively on an island

In [66]:
birds['wkilo'] = np.round(birds['body_mass_g'] / 1000, 1)

# Adelie in Biscoe

In [67]:
Adelie_Biscoe = birds[(birds['species'] == 'Adelie') &(birds['island'] == 'Biscoe')]

# Adelie in Dream

In [68]:
Adelie_Dream = birds[(birds['species'] == 'Adelie') &(birds['island'] == 'Dream')]

# Adelie in Torgersen

In [69]:
Adelie_Torgersen = birds[(birds['species'] == 'Adelie') &(birds['island'] == 'Torgersen')]

In [70]:
Adelie_Biscoe

,rowid,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex,year,weight,wkilo
20,21,Adelie,Biscoe,37.8,18.3,174.0,3400.0,female,2007,3.4,3.4
21,22,Adelie,Biscoe,37.7,18.7,180.0,3600.0,male,2007,3.6,3.6
22,23,Adelie,Biscoe,35.9,19.2,189.0,3800.0,female,2007,3.8,3.8
23,24,Adelie,Biscoe,38.2,18.1,185.0,3950.0,male,2007,4.0,4.0
24,25,Adelie,Biscoe,38.8,17.2,180.0,3800.0,male,2007,3.8,3.8
25,26,Adelie,Biscoe,35.3,18.9,187.0,3800.0,female,2007,3.8,3.8
26,27,Adelie,Biscoe,40.6,18.6,183.0,3550.0,male,2007,3.6,3.6
27,28,Adelie,Biscoe,40.5,17.9,187.0,3200.0,female,2007,3.2,3.2
28,29,Adelie,Biscoe,37.9,18.6,172.0,3150.0,female,2007,3.2,3.2
29,30,Adelie,Biscoe,40.5,18.9,180.0,3950.0,male,2007,4.0,4.0
50,51,Adelie,Biscoe,39.6,17.7,186.0,3500.0,female,2008,3.5,3.5
51,52,Adelie,Biscoe,40.1,18.9,188.0,4300.0,male,2008,4.3,4.3
52,53,Adelie,Biscoe,35.0,17.9,190.0,3450.0,female,2008,3.4,3.4
53,54,Adelie,Biscoe,42.0,19.5,200.0,4050.0,male,2008,4.0,4.0
54,55,Adelie,Biscoe,34.5,18.1,187.0,2900.0,female,2008,2.9,2.9
55,56,Adelie,Biscoe,41.4,18.6,191.0,3700.0,male,2008,3.7,3.7
56,57,Adelie,Biscoe,39.0,17.5,186.0,3550.0,female,2008,3.6,3.6
57,58,Adelie,Biscoe,40.6,18.8,193.0,3800.0,male,2008,3.8,3.8
58,59,Adelie,Biscoe,36.5,16.6,181.0,2850.0,female,2008,2.8,2.8
59,60,Adelie,Biscoe,37.6,19.1,194.0,3750.0,male,2008,3.8,3.8
60,61,Adelie,Biscoe,35.7,16.9,185.0,3150.0,female,2008,3.2,3.2
61,62,Adelie,Biscoe,41.3,21.1,195.0,4400.0,male,2008,4.4,4.4
62,63,Adelie,Biscoe,37.6,17.0,185.0,3600.0,female,2008,3.6,3.6
63,64,Adelie,Biscoe,41.1,18.2,192.0,4050.0,male,2008,4.0,4.0
64,65,Adelie,Biscoe,36.4,17.1,184.0,2850.0,female,2008,2.8,2.8
65,66,Adelie,Biscoe,41.6,18.0,192.0,3950.0,male,2008,4.0,4.0
66,67,Adelie,Biscoe,35.5,16.2,195.0,3350.0,female,2008,3.4,3.4
67,68,Adelie,Biscoe,41.1,19.1,188.0,4100.0,male,2008,4.1,4.1
100,101,Adelie,Biscoe,35.0,17.9,192.0,3725.0,female,2009,3.7,3.7
101,102,Adelie,Biscoe,41.0,20.0,203.0,4725.0,male,2009,4.7,4.7
102,103,Adelie,Biscoe,37.7,16.0,183.0,3075.0,female,2009,3.1,3.1
103,104,Adelie,Biscoe,37.8,20.0,190.0,4250.0,male,2009,4.2,4.2
104,105,Adelie,Biscoe,37.9,18.6,193.0,2925.0,female,2009,2.9,2.9
105,106,Adelie,Biscoe,39.7,18.9,184.0,3550.0,male,2009,3.6,3.6
106,107,Adelie,Biscoe,38.6,17.2,199.0,3750.0,female,2009,3.8,3.8
107,108,Adelie,Biscoe,38.2,20.0,190.0,3900.0,male,2009,3.9,3.9
108,109,Adelie,Biscoe,38.1,17.0,181.0,3175.0,female,2009,3.2,3.2
109,110,Adelie,Biscoe,43.2,19.0,197.0,4775.0,male,2009,4.8,4.8
110,111,Adelie,Biscoe,38.1,16.5,198.0,3825.0,female,2009,3.8,3.8
111,112,Adelie,Biscoe,45.6,20.3,191.0,4600.0,male,2009,4.6,4.6
112,113,Adelie,Biscoe,39.7,17.7,193.0,3200.0,female,2009,3.2,3.2
113,114,Adelie,Biscoe,42.2,19.5,197.0,4275.0,male,2009,4.3,4.3
114,115,Adelie,Biscoe,39.6,20.7,191.0,3900.0,female,2009,3.9,3.9
115,116,Adelie,Biscoe,42.7,18.3,196.0,4075.0,male,2009,4.1,4.1

In [71]:
Adelie_Dream

,rowid,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex,year,weight,wkilo
30,31,Adelie,Dream,39.5,16.7,178.0,3250.0,female,2007,3.2,3.2
31,32,Adelie,Dream,37.2,18.1,178.0,3900.0,male,2007,3.9,3.9
32,33,Adelie,Dream,39.5,17.8,188.0,3300.0,female,2007,3.3,3.3
33,34,Adelie,Dream,40.9,18.9,184.0,3900.0,male,2007,3.9,3.9
34,35,Adelie,Dream,36.4,17.0,195.0,3325.0,female,2007,3.3,3.3
35,36,Adelie,Dream,39.2,21.1,196.0,4150.0,male,2007,4.2,4.2
36,37,Adelie,Dream,38.8,20.0,190.0,3950.0,male,2007,4.0,4.0
37,38,Adelie,Dream,42.2,18.5,180.0,3550.0,female,2007,3.6,3.6
38,39,Adelie,Dream,37.6,19.3,181.0,3300.0,female,2007,3.3,3.3
39,40,Adelie,Dream,39.8,19.1,184.0,4650.0,male,2007,4.6,4.6
40,41,Adelie,Dream,36.5,18.0,182.0,3150.0,female,2007,3.2,3.2
41,42,Adelie,Dream,40.8,18.4,195.0,3900.0,male,2007,3.9,3.9
42,43,Adelie,Dream,36.0,18.5,186.0,3100.0,female,2007,3.1,3.1
43,44,Adelie,Dream,44.1,19.7,196.0,4400.0,male,2007,4.4,4.4
44,45,Adelie,Dream,37.0,16.9,185.0,3000.0,female,2007,3.0,3.0
45,46,Adelie,Dream,39.6,18.8,190.0,4600.0,male,2007,4.6,4.6
46,47,Adelie,Dream,41.1,19.0,182.0,3425.0,male,2007,3.4,3.4
47,48,Adelie,Dream,37.5,18.9,179.0,2975.0,male,2007,3.0,3.0
48,49,Adelie,Dream,36.0,17.9,190.0,3450.0,female,2007,3.4,3.4
49,50,Adelie,Dream,42.3,21.2,191.0,4150.0,male,2007,4.2,4.2
84,85,Adelie,Dream,37.3,17.8,191.0,3350.0,female,2008,3.4,3.4
85,86,Adelie,Dream,41.3,20.3,194.0,3550.0,male,2008,3.6,3.6
86,87,Adelie,Dream,36.3,19.5,190.0,3800.0,male,2008,3.8,3.8
87,88,Adelie,Dream,36.9,18.6,189.0,3500.0,female,2008,3.5,3.5
88,89,Adelie,Dream,38.3,19.2,189.0,3950.0,male,2008,4.0,4.0
89,90,Adelie,Dream,38.9,18.8,190.0,3600.0,female,2008,3.6,3.6
90,91,Adelie,Dream,35.7,18.0,202.0,3550.0,female,2008,3.6,3.6
91,92,Adelie,Dream,41.1,18.1,205.0,4300.0,male,2008,4.3,4.3
92,93,Adelie,Dream,34.0,17.1,185.0,3400.0,female,2008,3.4,3.4
93,94,Adelie,Dream,39.6,18.1,186.0,4450.0,male,2008,4.4,4.4
94,95,Adelie,Dream,36.2,17.3,187.0,3300.0,female,2008,3.3,3.3
95,96,Adelie,Dream,40.8,18.9,208.0,4300.0,male,2008,4.3,4.3
96,97,Adelie,Dream,38.1,18.6,190.0,3700.0,female,2008,3.7,3.7
97,98,Adelie,Dream,40.3,18.5,196.0,4350.0,male,2008,4.4,4.4
98,99,Adelie,Dream,33.1,16.1,178.0,2900.0,female,2008,2.9,2.9
99,100,Adelie,Dream,43.2,18.5,192.0,4100.0,male,2008,4.1,4.1
132,133,Adelie,Dream,36.8,18.5,193.0,3500.0,female,2009,3.5,3.5
133,134,Adelie,Dream,37.5,18.5,199.0,4475.0,male,2009,4.5,4.5
134,135,Adelie,Dream,38.1,17.6,187.0,3425.0,female,2009,3.4,3.4
135,136,Adelie,Dream,41.1,17.5,190.0,3900.0,male,2009,3.9,3.9
136,137,Adelie,Dream,35.6,17.5,191.0,3175.0,female,2009,3.2,3.2
137,138,Adelie,Dream,40.2,20.1,200.0,3975.0,male,2009,4.0,4.0
138,139,Adelie,Dream,37.0,16.5,185.0,3400.0,female,2009,3.4,3.4
139,140,Adelie,Dream,39.7,17.9,193.0,4250.0,male,2009,4.2,4.2
140,141,Adelie,Dream,40.2,17.1,193.0,3400.0,female,2009,3.4,3.4
141,142,Adelie,Dream,40.6,17.2,187.0,3475.0,male,2009,3.5,3.5
142,143,Adelie,Dream,32.1,15.5,188.0,3050.0,female,2009,3.0,3.0
143,144,Adelie,Dream,40.7,17.0,190.0,3725.0,male,2009,3.7,3.7
144,145,Adelie,Dream,37.3,16.8,192.0,3000.0,female,2009,3.0,3.0
145,146,Adelie,Dream,39.0,18.7,185.0,3650.0,male,2009,3.6,3.6
146,147,Adelie,Dream,39.2,18.6,190.0,4250.0,male,2009,4.2,4.2
147,148,Adelie,Dream,36.6,18.4,184.0,3475.0,female,2009,3.5,3.5
148,149,Adelie,Dream,36.0,17.8,195.0,3450.0,female,2009,3.4,3.4
149,150,Adelie,Dream,37.8,18.1,193.0,3750.0,male,2009,3.8,3.8
150,151,Adelie,Dream,36.0,17.1,187.0,3700.0,female,2009,3.7,3.7
151,152,Adelie,Dream,41.5,18.5,201.0,4000.0,male,2009,4.0,4.0

In [72]:
Adelie_Torgersen

,rowid,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex,year,weight,wkilo
0,1,Adelie,Torgersen,39.10000,18.70000,181.000000,3750.000000,male,2007,3.8,3.8
1,2,Adelie,Torgersen,39.50000,17.40000,186.000000,3800.000000,female,2007,3.8,3.8
2,3,Adelie,Torgersen,40.30000,18.00000,195.000000,3250.000000,female,2007,3.2,3.2
3,4,Adelie,Torgersen,43.92193,17.15117,200.915205,4201.754386,male,2007,4.2,4.2
4,5,Adelie,Torgersen,36.70000,19.30000,193.000000,3450.000000,female,2007,3.4,3.4
5,6,Adelie,Torgersen,39.30000,20.60000,190.000000,3650.000000,male,2007,3.6,3.6
6,7,Adelie,Torgersen,38.90000,17.80000,181.000000,3625.000000,female,2007,3.6,3.6
7,8,Adelie,Torgersen,39.20000,19.60000,195.000000,4675.000000,male,2007,4.7,4.7
8,9,Adelie,Torgersen,34.10000,18.10000,193.000000,3475.000000,male,2007,3.5,3.5
9,10,Adelie,Torgersen,42.00000,20.20000,190.000000,4250.000000,male,2007,4.2,4.2
10,11,Adelie,Torgersen,37.80000,17.10000,186.000000,3300.000000,male,2007,3.3,3.3
11,12,Adelie,Torgersen,37.80000,17.30000,180.000000,3700.000000,male,2007,3.7,3.7
12,13,Adelie,Torgersen,41.10000,17.60000,182.000000,3200.000000,female,2007,3.2,3.2
13,14,Adelie,Torgersen,38.60000,21.20000,191.000000,3800.000000,male,2007,3.8,3.8
14,15,Adelie,Torgersen,34.60000,21.10000,198.000000,4400.000000,male,2007,4.4,4.4
15,16,Adelie,Torgersen,36.60000,17.80000,185.000000,3700.000000,female,2007,3.7,3.7
16,17,Adelie,Torgersen,38.70000,19.00000,195.000000,3450.000000,female,2007,3.4,3.4
17,18,Adelie,Torgersen,42.50000,20.70000,197.000000,4500.000000,male,2007,4.5,4.5
18,19,Adelie,Torgersen,34.40000,18.40000,184.000000,3325.000000,female,2007,3.3,3.3
19,20,Adelie,Torgersen,46.00000,21.50000,194.000000,4200.000000,male,2007,4.2,4.2
68,69,Adelie,Torgersen,35.90000,16.60000,190.000000,3050.000000,female,2008,3.0,3.0
69,70,Adelie,Torgersen,41.80000,19.40000,198.000000,4450.000000,male,2008,4.4,4.4
70,71,Adelie,Torgersen,33.50000,19.00000,190.000000,3600.000000,female,2008,3.6,3.6
71,72,Adelie,Torgersen,39.70000,18.40000,190.000000,3900.000000,male,2008,3.9,3.9
72,73,Adelie,Torgersen,39.60000,17.20000,196.000000,3550.000000,female,2008,3.6,3.6
73,74,Adelie,Torgersen,45.80000,18.90000,197.000000,4150.000000,male,2008,4.2,4.2
74,75,Adelie,Torgersen,35.50000,17.50000,190.000000,3700.000000,female,2008,3.7,3.7
75,76,Adelie,Torgersen,42.80000,18.50000,195.000000,4250.000000,male,2008,4.2,4.2
76,77,Adelie,Torgersen,40.90000,16.80000,191.000000,3700.000000,female,2008,3.7,3.7
77,78,Adelie,Torgersen,37.20000,19.40000,184.000000,3900.000000,male,2008,3.9,3.9
78,79,Adelie,Torgersen,36.20000,16.10000,187.000000,3550.000000,female,2008,3.6,3.6
79,80,Adelie,Torgersen,42.10000,19.10000,195.000000,4000.000000,male,2008,4.0,4.0
80,81,Adelie,Torgersen,34.60000,17.20000,189.000000,3200.000000,female,2008,3.2,3.2
81,82,Adelie,Torgersen,42.90000,17.60000,196.000000,4700.000000,male,2008,4.7,4.7
82,83,Adelie,Torgersen,36.70000,18.80000,187.000000,3800.000000,female,2008,3.8,3.8
83,84,Adelie,Torgersen,35.10000,19.40000,193.000000,4200.000000,male,2008,4.2,4.2
116,117,Adelie,Torgersen,38.60000,17.00000,188.000000,2900.000000,female,2009,2.9,2.9
117,118,Adelie,Torgersen,37.30000,20.50000,199.000000,3775.000000,male,2009,3.8,3.8
118,119,Adelie,Torgersen,35.70000,17.00000,189.000000,3350.000000,female,2009,3.4,3.4
119,120,Adelie,Torgersen,41.10000,18.60000,189.000000,3325.000000,male,2009,3.3,3.3
120,121,Adelie,Torgersen,36.20000,17.20000,187.000000,3150.000000,female,2009,3.2,3.2
121,122,Adelie,Torgersen,37.70000,19.80000,198.000000,3500.000000,male,2009,3.5,3.5
122,123,Adelie,Torgersen,40.20000,17.00000,176.000000,3450.000000,female,2009,3.4,3.4
123,124,Adelie,Torgersen,41.40000,18.50000,202.000000,3875.000000,male,2009,3.9,3.9
124,125,Adelie,Torgersen,35.20000,15.90000,186.000000,3050.000000,female,2009,3.0,3.0
125,126,Adelie,Torgersen,40.60000,19.00000,199.000000,4000.000000,male,2009,4.0,4.0
126,127,Adelie,Torgersen,38.80000,17.60000,191.000000,3275.000000,female,2009,3.3,3.3
127,128,Adelie,Torgersen,41.50000,18.30000,195.000000,4300.000000,male,2009,4.3,4.3
128,129,Adelie,Torgersen,39.00000,17.10000,191.000000,3050.000000,female,2009,3.0,3.0
129,130,Adelie,Torgersen,44.10000,18.00000,210.000000,4000.000000,male,2009,4.0,4.0
130,131,Adelie,Torgersen,38.50000,17.90000,190.000000,3325.000000,female,2009,3.3,3.3
131,132,Adelie,Torgersen,43.10000,19.20000,197.000000,3500.000000,male,2009,3.5,3.5

In [73]:
Gentoo_Torgersen = birds[(birds['species'] == 'Gentoo') &(birds['island'] == 'Torgersen')]

In [74]:
Gentoo_Torgersen

Empty DataFrame
Columns: [rowid, species, island, bill_length_mm, bill_depth_mm, flipper_length_mm, body_mass_g, sex, year, weight, wkilo]
Index: []

In [75]:
Gentoo_Adelie = birds[(birds['species'] == 'Gentoo') &(birds['island'] == 'Adelie')]

In [76]:
Gentoo_Adelie

Empty DataFrame
Columns: [rowid, species, island, bill_length_mm, bill_depth_mm, flipper_length_mm, body_mass_g, sex, year, weight, wkilo]
Index: []

In [77]:
Gentoo_Biscoe = birds[(birds['species'] == 'Gentoo') &(birds['island'] == 'Biscoe')]

In [78]:
Gentoo_Biscoe

,rowid,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex,year,weight,wkilo
152,153,Gentoo,Biscoe,46.10000,13.20000,211.000000,4500.000000,female,2007,4.5,4.5
153,154,Gentoo,Biscoe,50.00000,16.30000,230.000000,5700.000000,male,2007,5.7,5.7
154,155,Gentoo,Biscoe,48.70000,14.10000,210.000000,4450.000000,female,2007,4.4,4.4
155,156,Gentoo,Biscoe,50.00000,15.20000,218.000000,5700.000000,male,2007,5.7,5.7
156,157,Gentoo,Biscoe,47.60000,14.50000,215.000000,5400.000000,male,2007,5.4,5.4
...,...,...,...,...,...,...,...,...,...,...,...
271,272,Gentoo,Biscoe,43.92193,17.15117,200.915205,4201.754386,male,2009,4.2,4.2
272,273,Gentoo,Biscoe,46.80000,14.30000,215.000000,4850.000000,female,2009,4.8,4.8
273,274,Gentoo,Biscoe,50.40000,15.70000,222.000000,5750.000000,male,2009,5.8,5.8
274,275,Gentoo,Biscoe,45.20000,14.80000,212.000000,5200.000000,female,2009,5.2,5.2
275,276,Gentoo,Biscoe,49.90000,16.10000,213.000000,5400.000000,male,2009,5.4,5.4

In [79]:
total = adelie.count() = gentoo.count() = chains.count()

SyntaxError: cannot assign to function call (4100286499.py, line 1)

# insight #1

# Gentoo penguins are live exclusively in the biscoe island

In [ ]:
adelie_dream = getPenguin("Adelie", "Dream")
adelie_dream.info()

In [ ]:
adelie_torg = getPenguin("Adelie", "Torgersen")
adelie_torg.info()

In [ ]:
adelie_gen = getPenguin("Adelie", "Gentoo")
adelie_gen.info()

# insigth #2

# Adelie penguins are found in biscoe turgersen

In [ ]:
adelie_gen = getPenguin("Adelie", "Gentoo")
adelie_gen.info()

 # insigth #3

# Chinstrap 

# Does the island impact the body mass of a birds species

In [ ]:

A = np.round(birds[birds['species'] == "Adelie"]['wkilo'].mean(),1)

In [ ]:
A

# insigth #4

# The island doesnt have an impact on the weight of the Adelie

In [ ]:
Gentoo_Biscoe_w = np.round(Gentoo_Biscoe['wkilo'].mean(), 1)

In [ ]:
Gentoo_Biscoe_w

In [ ]:
Gentoo_Dream_w = np.round(Gentoo_Biscoe['wkilo'].mean(), 1)
Gentoo_Dream_w

In [ ]:
Gentoo_Torgersen_w = np.round(Gentoo_Biscoe['wkilo'].mean(), 1)
Gentoo_Torgersen_w

# insigth #5

# The Average weight of Adelie Penguins is: 3.7

In [ ]:
avg_chains = np.round(chains['weight'].mean(), 2)
avg_chains

# insigth #6

# Does island  doesnt have an impact on weight of the chinstrap

# insigth #7

# the haviest species among the three species in the dataset in the Gentoo penguin

In [ ]:
birds_agg = birds.groupby(['species','island']).size()
birds_agg

# insigth #8

# The most  recorded male adelie penguinswas from year 2007 and 2010 on the dream island

In [ ]:
penguins_agg4 = np.round(birds.groupby(['species','sex'])['wkilo'].mean())
penguins_agg4.unstack()

# insigth #9

# What is heavier adelie male or female

In [ ]:
penguin_agg2 = np.round(birds.groupby(['species', 'island'])['wkilo'].mean(),1)
penguin_agg2

# insigth #10

# What year has the highest recorded male or female chinstrap both

# insigth #11 

# What year has the highest recorded male or female , Gentoo both

# Does the Bill  lenght effects the size of the depth?

In [ ]:
b_depp_lenght_cor = birds['bill_length_mm'].corr(birds['bill_depth_mm'])

In [ ]:
b_depp_lenght_cor

# insigth #12

# Bill Lenght has no Correlation with Bill depth

# Does bill length effects the size of the mass?

In [ ]:
b1_depp_lenght_cor = birds['body_mass_g'].corr(birds['bill_length_mm'])

In [ ]:
b1_depp_lenght_cor

# insigth #13

# The body mass has no effects on the bill length

# Does bill length Correlation the size of the flipper lenth?

In [ ]:
b2_depp_lenght_cor = birds['flipper_length_mm'].corr(birds['bill_length_mm'])

In [ ]:
b2_depp_lenght_cor

# insigth #14

# The biull length  has no effect on the flipper length

# Does body mass has Correlation on the flipper length?

In [ ]:
b3_depp_lenght_cor = birds['body_mass_g'].corr(birds['flipper_length_mm'])

b3_depp_lenght_cor

# insigth # 15

# The body mass has no Correlation on the flipper length

In [ ]:
pip install scipy

# Correlation between qualitative and quantitative

# Sex and Body mass

In [ ]:
from scipy.stats import f_oneway

In [80]:
birds[birds['sex'] == 'male']['body_mass_g']

0      3750.000000
3      4201.754386
5      3650.000000
7      4675.000000
8      3475.000000
          ...
334    3800.000000
336    3950.000000
339    4000.000000
341    3775.000000
342    4100.000000
Name: body_mass_g, Length: 179, dtype: float64

In [81]:
birds[birds['sex'] == 'female']['body_mass_g']

1      3800.0
2      3250.0
4      3450.0
6      3625.0
12     3200.0
        ...
335    3525.0
337    3650.0
338    3650.0
340    3400.0
343    3775.0
Name: body_mass_g, Length: 165, dtype: float64

In [82]:
f_stats, p_value = f_oneway(birds[birds['sex'] == 'male']['body_mass_g'],
         birds[birds['sex'] == 'female']['body_mass_g'])
print(p_value)

NameError: name 'f_oneway' is not defined

# insigth #16
# There is correlation  between sex and body mass

In [ ]:
birds.info()